// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyctjveisbgkepjrucji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5Y3RqdmVpc2Jna2VwanJ1Y2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzMzMzAsImV4cCI6MjA3NDMwOTMzMH0.jJ51rHQYDgIKMygeB1P6bkM1MfRrPViURcaqISQeMbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});