// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvljdyhkzybtqukglkwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bGpkeWhrenlidHF1a2dsa3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjQ5OTQsImV4cCI6MjA3NDMwMDk5NH0.WVUV-Ff6SBqTfhc3u8nOW7Ukl8iDrqwHx1vTvIvnqWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});